[package]
name = "server"
version = "0.1.0"
authors = ["bbsmithy <bsmith@cartrawler.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
mongodb = "*"
serde = { features = ["derive"] }


[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["mongodb_pool", "json"]