[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8080
workers = 2
keep_alive = 5
log = "critical"
limits = { forms = 32768 }

[global.databases]
sqlite_logs = { url = "postgresql://utveuly3nqvusv6dobvo:7IOji0EeGz3rss8mimrJ@btt3z8bmoskqs6wnlfnx-postgresql.services.clever-cloud.com:5432/btt3z8bmoskqs6wnlfnx" }
