[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8080
workers = 2
keep_alive = 5
log = "critical"
limits = { forms = 32768 }

[global.databases]
tigum_db = { url = "mongodb://bbsmithy:thepowerofchristy123@cluster0-shard-00-00-8wole.mongodb.net:27017,cluster0-shard-00-01-8wole.mongodb.net:27017,cluster0-shard-00-02-8wole.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority" }

