[debug]
address = "127.0.0.1"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8080
workers = 2
keep_alive = 5
log = "critical"
limits = { forms = 32768 }


[global.databases]
tigum_db = { url = "postgresql://utveuly3nqvusv6dobvo:sL6h3t1m7rCDR7wN0R4h@b28od1tez5dxzu9fedjf-postgresql.services.clever-cloud.com:5209/b28od1tez5dxzu9fedjf", pool = 2 }
